spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    datasource: 0
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 8090
    username: guest
    password: guest
server:
  port: 8090

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
swagger:
  enabled: true
  